spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    username: "sa"
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8081
graphite:
  host: "https://www.hostedgraphite.com/api/v1/sink"
  apiKey: ${HOSTEDGRAPHITE_APIKEY}
