spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    username: "sa"
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8081

graphite:
  host: "47b2343c.carbon.hostedgraphite.com"
  apiKey: "fdabd6ad-85c3-414f-9384-ad7c70a72a0a"
